import { useState } from 'react';
import Layout from '../components/Layout';
import Feedback from '../components/Feedback';
import { useCantina } from '../hooks/useCantina';
import { dataLocal } from '../services/catalogo';
const blank = { nome:'', descricao:'', categoria:'Salgados', preco:'', estoque:'', alergenos:'' };
export default function GestaoItens() {
  const { estado, service } = useCantina();
  const [form, setForm] = useState(blank), [feedback, setFeedback] = useState({}), [search, setSearch] = useState(''), [edit, setEdit] = useState({});
  const items = estado.itens.filter((i) => i.categoria !== 'Combos' && i.nome.toLowerCase().includes(search.toLowerCase()));
  function submit(e) { e.preventDefault(); try { service.salvarItem(form); setForm(blank); setFeedback({ sucesso: 'Item salvo na demonstração.' }); } catch(err) { setFeedback({ erro:err.message }); } }
  function saveInline(i) { try { service.salvarItem({ ...i, preco: edit[i.id]?.preco ?? i.preco, estoque: Number(edit[i.id]?.estoque ?? i.estoque), alergenos: i.alergenos.join(',') }); setFeedback({ sucesso:'Estoque e preço atualizados.' }); } catch(err) { setFeedback({ erro:err.message }); } }
  return <Layout perfil="Admin" nome="Gestão do cardápio"><div className="section-head"><span className="eyebrow">Catálogo e estoque</span><h1>Gestão de itens</h1><p className="lead">Preços, estoque, alérgenos e itens ativos em uma visão.</p></div><Feedback {...feedback}/>
    <div className="two-column" style={{marginTop:20}}><section className="surface pad"><div className="between wrap"><h2>Itens</h2><input className="input" style={{maxWidth:260}} type="search" aria-label="Buscar item" placeholder="Buscar item" value={search} onChange={(e) => setSearch(e.target.value)}/></div><div className="table-scroll"><table className="data-table"><thead><tr><th>Item e descrição</th><th>Preço</th><th>Estoque</th><th>Alérgenos</th><th>Oferta hoje</th><th>Ativo</th><th>Ação</th></tr></thead><tbody>{items.map((i) => <tr key={i.id}><td><strong>{i.nome}</strong><div className="small muted">{i.descricao}</div></td><td><input aria-label={'Preço de '+i.nome} className="input" type="number" min=".01" step=".01" style={{width:90}} value={edit[i.id]?.preco ?? i.preco} onChange={(e) => setEdit({...edit,[i.id]:{...edit[i.id],preco:e.target.value}})}/></td><td><input aria-label={'Estoque de '+i.nome} className="input" type="number" min="0" step="1" style={{width:78}} value={edit[i.id]?.estoque ?? i.estoque} onChange={(e) => setEdit({...edit,[i.id]:{...edit[i.id],estoque:e.target.value}})}/></td><td className="small">{i.alergenos.join(', ') || '—'}</td><td><div className="stack small" style={{gap:5}}>{[['manha','Manhã'],['tarde','Tarde']].map(([key,label]) => <label key={key} className="row"><input type="checkbox" checked={Boolean(estado.ofertas?.[dataLocal()]?.[key]?.includes(i.id))} onChange={(e) => service.definirOferta(i.id,key,e.target.checked)}/>{label}</label>)}</div></td><td><span className={'badge '+(i.ativo?'':'amber')}>{i.ativo?'Sim':'Não'}</span></td><td><div className="row"><button className="btn soft" onClick={() => saveInline(i)}>Salvar</button>{i.ativo && <button className="btn danger" onClick={() => { service.desativarItem(i.id); setFeedback({ sucesso:'Item desativado.' }); }}>Desativar</button>}</div></td></tr>)}</tbody></table></div><p className="hint">Preços exibidos em reais. Edições feitas aqui são demonstrativas.</p></section>
      <form className="surface pad stack" onSubmit={submit}><h2>Novo item</h2><label className="field">Nome<input className="input" required value={form.nome} onChange={(e) => setForm({...form,nome:e.target.value})}/></label><label className="field">Descrição<textarea className="input" required rows="3" value={form.descricao} onChange={(e) => setForm({...form,descricao:e.target.value})}/></label><label className="field">Categoria<select className="input" value={form.categoria} onChange={(e) => setForm({...form,categoria:e.target.value})}><option>Salgados</option><option>Doces</option><option>Bebidas</option></select></label><div className="grid-2"><label className="field">Preço (R$)<input className="input" type="number" min=".01" step=".01" required value={form.preco} onChange={(e) => setForm({...form,preco:e.target.value})}/></label><label className="field">Estoque<input className="input" type="number" min="0" step="1" required value={form.estoque} onChange={(e) => setForm({...form,estoque:e.target.value})}/></label></div><label className="field">Alérgenos, separados por vírgula<input className="input" value={form.alergenos} onChange={(e) => setForm({...form,alergenos:e.target.value})}/></label><button className="btn">Criar item</button></form></div>
    <span className="small muted">Total de itens visíveis: {items.length}</span></Layout>;
}