import { useState } from 'react';
import Feedback from '../components/Feedback';
import Quantidade from '../components/Quantidade';
import { useCantina } from '../hooks/useCantina';
import { intervaloAberto, dataLocal } from '../services/catalogo';
import { displayDate, disponivelNoIntervalo, money, statusPedido } from '../services/cantinaService';
export default function Historico() {
  const { estado, usuario, service } = useCantina(), aluno = usuario?.papel === 'Aluno' ? usuario : estado.usuarios.find((u) => u.id === 'aluno-1');
  const [filtro,setFiltro] = useState('Todos'), [editing,setEditing] = useState(null), [quantities,setQuantities] = useState({}), [feedback,setFeedback] = useState({});
  const pedidos = estado.pedidos.filter((p) => p.usuarioId === aluno?.id && (filtro==='Todos' || (filtro==='Hoje' && p.data===dataLocal()) || (filtro==='Mês' && p.data.slice(0,7)===dataLocal().slice(0,7))));
  function begin(p) { setEditing(p.id); setQuantities(Object.fromEntries(p.itens.map((i) => [i.itemId,i.quantidade]))); setFeedback({}); }
  function run(fn,message) { try { fn(); setEditing(null); setFeedback({ sucesso:message }); } catch(e) { setFeedback({ erro:e.message }); } }
  return <><div className="section-head"><span className="eyebrow">Acompanhamento</span><h1>Meus pedidos</h1><p className="lead">Acompanhe a retirada e altere pedidos Abertos enquanto o prazo permitir.</p></div><Feedback {...feedback}/><div className="pill-tabs" style={{margin:'20px 0'}}>{['Todos','Hoje','Mês'].map((v) => <button key={v} aria-pressed={filtro===v} onClick={() => setFiltro(v)}>{v}</button>)}</div>
    <div className="stack">{pedidos.map((p) => { const status=statusPedido(p), canEdit=p.status==='Aberto' && intervaloAberto(p.intervalo,p.data); return <article className="surface pad" key={p.id}><div className="between wrap"><div><span className="eyebrow">{displayDate(p.data)} · {p.intervalo || 'Balcão'}</span><h2 style={{margin:'8px 0'}}>Pedido {p.id}</h2><span className={'badge '+(status==='Cancelado'?'red':status==='Confirmado'?'amber':'')}>{status}</span></div><div className="right"><span className="muted small">Total</span><div className="metric">{money(p.total)}</div>{status==='Confirmado' && <div className="badge">Código de retirada: {p.codigoRetirada}</div>}</div></div><div className="divider"/>
      {p.itens.map((i) => <div className="line" key={i.itemId}><span>{i.quantidade} × {i.nome}</span><span>{money(i.subtotal)}</span></div>)}
      {canEdit && <div className="row wrap no-print" style={{marginTop:20}}><button className="btn secondary" onClick={() => begin(p)}>Alterar</button><button className="btn danger" onClick={() => run(() => service.cancelarPedido(p.id),'Pedido cancelado e estoque restituído.')}>Cancelar</button></div>}
      {editing===p.id && <div className="surface pad" style={{marginTop:18,background:'#f8fbf8'}}><h3>Alterar itens</h3><p className="hint">A diferença de valor será lançada ou estornada na conta.</p>{estado.itens.filter((i) => disponivelNoIntervalo(estado,i,p.intervalo,p.data) && i.categoria!=='Combos').map((i) => <div className="line" key={i.id}><span>{i.nome} · {money(i.preco)}</span><Quantidade nome={i.nome} valor={quantities[i.id] || 0} maximo={i.estoque+(p.itens.find((l) => l.itemId===i.id)?.quantidade || 0)} aoMudar={(n) => setQuantities({...quantities,[i.id]:n})}/></div>)}<div className="row" style={{marginTop:15}}><button className="btn" onClick={() => run(() => service.alterarPedido(p.id,quantities),'Pedido alterado.')}>Salvar alterações</button><button className="btn secondary" onClick={() => setEditing(null)}>Fechar</button></div></div>}</article>; })}{!pedidos.length && <div className="empty">Nenhum pedido no período.</div>}</div></>;
}
