import { useState } from 'react';
import Layout from '../components/Layout';
import Feedback from '../components/Feedback';
import { useCantina } from '../hooks/useCantina';
export default function MetodosPagamento({ adultoId = 'adulto-1' }) {
  const { estado, service } = useCantina(), adulto = estado.usuarios.find((u) => u.id === adultoId);
  const [form, setForm] = useState({ tipo: 'Pix', apelido: '', ultimosDigitos: '', padrao: false }), [feedback, setFeedback] = useState({});
  function submit(e) { e.preventDefault(); try { service.salvarMetodo(form); setForm({ tipo: 'Pix', apelido: '', ultimosDigitos: '', padrao: false }); setFeedback({ sucesso: 'Método fictício adicionado.' }); } catch (err) { setFeedback({ erro: err.message }); } }
  return <Layout perfil="Responsável" nome={adulto?.nome}><div className="section-head"><span className="eyebrow">Pagamento demonstrativo</span><h1>Meios de pagamento</h1><p className="lead">Cadastre somente dados fictícios para a demonstração.</p></div><Feedback {...feedback}/>
    <div className="two-column" style={{marginTop:20}}><section className="surface pad"><h2>Métodos cadastrados</h2>{estado.metodos.map((m) => <div className="line wrap" key={m.id}><div><strong>{m.apelido}</strong><div className="small muted">{m.tipo === 'Pix' ? 'Pix' : 'Cartão terminado em ' + m.ultimosDigitos}</div></div><div className="row">{m.padrao ? <span className="badge">Padrão</span> : <button className="btn secondary no-print" onClick={() => { service.definirMetodoPadrao(m.id); setFeedback({ sucesso: 'Método padrão atualizado.' }); }}>Definir padrão</button>}</div></div>)}</section>
      <form className="surface pad stack" onSubmit={submit}><h2>Novo método</h2><label className="field">Tipo<select className="input" value={form.tipo} onChange={(e) => setForm({ ...form, tipo: e.target.value })}><option value="Pix">Pix</option><option value="Cartao">Cartão</option></select></label><label className="field">Apelido<input className="input" required value={form.apelido} onChange={(e) => setForm({ ...form, apelido: e.target.value })} placeholder="Ex.: Meu cartão"/></label>{form.tipo === 'Cartao' && <label className="field">Últimos 4 dígitos fictícios<input className="input" maxLength="4" inputMode="numeric" value={form.ultimosDigitos} onChange={(e) => setForm({ ...form, ultimosDigitos: e.target.value })}/></label>}<label className="row small"><input type="checkbox" checked={form.padrao} onChange={(e) => setForm({ ...form, padrao: e.target.checked })}/> Marcar como padrão</label><button className="btn">Salvar método</button></form></div></Layout>;
}