import { useState } from 'react';
import Feedback from '../components/Feedback';
import { useCantina } from '../hooks/useCantina';
import { money } from '../services/cantinaService';
export default function Perfil() {
  const { estado, usuario, service } = useCantina(), aluno = usuario?.papel==='Aluno'?usuario:estado.usuarios.find((u)=>u.id==='aluno-1');
  const [nome,setNome]=useState(aluno?.nome||''), [email,setEmail]=useState(aluno?.email||''), [feedback,setFeedback]=useState({});
  function submit(e) { e.preventDefault(); try { service.atualizarPerfil({nome,email}); setFeedback({sucesso:'Perfil demonstrativo atualizado.'}); } catch(err) { setFeedback({erro:err.message}); } }
  return <><div className="section-head"><span className="eyebrow">Dados pessoais</span><h1>Meu perfil</h1><p className="lead">Informações da conta do aluno e saldo atualizado.</p></div><Feedback {...feedback}/><div className="grid-2" style={{marginTop:20}}><section className="surface pad"><div className="image-slot round"/><h2 style={{marginTop:14}}>{aluno?.nome}</h2><span className="badge">Aluno · {aluno?.turma}</span><div className="divider"/><span className="muted small">Saldo</span><div className="metric">{money(aluno?.saldo)}</div>{aluno?.saldo<0 && <div className="alert">Fiado: {money(-aluno.saldo)} de R$ 250,00</div>}<p className="muted small" style={{marginTop:12}}>Seu limite diário é definido pelo responsável: {aluno?.limiteDiario==null?'não definido':money(aluno.limiteDiario)}</p><p className="muted small">Restrições: {aluno?.restricoes?.join(', ')||'nenhuma'}</p></section><form className="surface pad stack" onSubmit={submit}><h2>Informações de contato</h2><label className="field">Nome<input className="input" required value={nome} onChange={(e)=>setNome(e.target.value)}/></label><label className="field">E-mail<input className="input" type="email" required value={email} onChange={(e)=>setEmail(e.target.value)}/></label><p className="hint">A alteração de limite e restrições é feita pelo responsável.</p><button className="btn">Salvar dados</button></form></div></>;
}
